#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/radio_heads/.vscode-server/cli/servers/Stable-385651c938df8a906869babee516bffd0ddb9829/server/node" "/home/radio_heads/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"